env:
  es6: true
  node: true
  mocha: true
extends:
  - google
  - eslint:recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: script
rules:
  array-bracket-spacing:
    - error
    - always
  camelcase: off
  eol-last:
    - error
    - always
  guard-for-in: off
  max-len: off
  no-multiple-empty-lines:
    - error
    - max: 2
      maxBOF: 0
      maxEOF: 1
  no-template-curly-in-string: error
  no-undef: error
  no-useless-concat: error
  object-curly-spacing:
    - error
    - always
  one-var: off
  padded-blocks:
    - error
    - blocks: never
      switches: never
  quotes:
    - error
    - single
    - allowTemplateLiterals: false
  require-jsdoc: off
  semi:
    - error
    - never
  strict:
    - error
    - global
overrides:
  - files: '**/*.ts'
    plugins:
      - eslint-plugin-tsdoc
    extends:
      - plugin:@typescript-eslint/recommended
    parser: '@typescript-eslint/parser'
    parserOptions:
      sourceType: module
    rules:
      indent: off # conflicts with @typescript-eslint/indent
      no-undef: off # conflicts with automatically imported types
      valid-jsdoc: off # conflicts with tsdoc/syntax
      tsdoc/syntax: error
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/indent':
        - error
        - 2
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-unused-vars': error
      '@typescript-eslint/no-var-requires': off
